name: Triggering Render Deployment
on:
  workflow-run:
    workflows: ["Testing"]
    branches: [main]
    types: 
      - completed
jobs:
  main:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID_BH  }}?key=${{ secrets.RENDER_API_KEY_BH }}